[package]
name = "ballistik-demo"
version = "0.1.0"
authors = ["Alin Andersen <alin.porcic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ballistik = { path = "../ballistik" }